# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_ACCESS_TOKEN: ${{secrets.PACKAGES_TOKEN_GITHUB}}
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: '0'
    - name: reattach HEAD to Head Ref
      run: git checkout "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref != ''
    - name: reattach HEAD to Ref
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref == ''
    - name: Add auth token for npm packages
      run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN_GITHUB }}\n@indriver:registry=https://npm.pkg.github.com" > .npmrc
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
          node-version: 16
    - name: Cache .pnpm-store
      uses: actions/cache@v1
      with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node16-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: ðŸ’ˆ Node
      run: echo "v`node -v`"
    - name: ðŸ’ˆ NPM
      run: echo "v`npm -v`"
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
    - name: ðŸŽˆ Install pnpm
      run: npm install -g pnpm
    - name: ðŸŽˆ Install dependencies
      run: pnpm i
    - name: Show folder
      run: echo "`ls -la`"
    - name: ðŸ§¬ Build packages
      run: pnpm build:js
